### ISSUE TITLE
Loading Notes for Leads

### ISSUE THREAD

**Issue by dbroking-sixcel** [bullhorn/dataloader#326] opened 2020-10-16 15:42 UTC
### Description

Loading notes for leads - data loader is showing that they loaded successfully - however, they are not viewable via the UI

### Steps to Reproduce

load files
review results

##### Expected behavior:

expect to see notes in UI

##### Actual behavior:

no notes are visible via the UI

##### Reproduces how often:

100%

### Additional Information

[Notes_Leads.zip](https://github.com/bullhorn/dataloader/files/5392704/Notes_Leads.zip)

**Comment by ndickerson** [comment] 2020-10-19 13:47
Data Loader is simply a translator - it takes data in the form of CSV rows/columns and translates them to payloads in Rest API calls. If there’s an issue with notes not showing up in an environment, then troubleshooting should be done at the Rest API call level, to cut out Data Loader as the source of the issue. I would do the following:

1. Query for the IDs that have been loaded by Data Loader and determine if they exist when queried via the API
2. Try manually creating a new note via the UI and determine if they show up in the UI
3. Try manually creating a new note via the API and determine if they show up in the UI

That should pinpoint where the issue is at in the environment.

**Comment by ndickerson** [comment] 2020-10-29 13:42
Marking this as resolved since there is no broken behavior in Data Loader itself, it is just the UI viewing, which can depend on indexes and other events being processed prior to viewing.

**Closed by ndickerson** 2020-10-29 13:42 UTC
